import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {props.data.map((ev: any) => (
          <a href={`/events/${ev.id}`} key={ev.id}>
            <Image src={ev.image} width="500" height="300" alt="images" />
          </a>
        ))}

        <a href="events/Mongolia">
          <img src="" alt="" />
          <h2>Events in Mongolia</h2>
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Optio hic
            assumenda veniam? Asperiores unde ab possimus alias cum aliquid,
            temporibus qui optio non, doloremque, dignissimos laboriosam omnis
            adipisci soluta magni.
          </p>
        </a>
        <a href="events/Seattle">
          <img src="" alt="" />
          <h2>Events in Seattle</h2>
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Optio hic
            assumenda veniam? Asperiores unde ab possimus alias cum aliquid,
            temporibus qui optio non, doloremque, dignissimos laboriosam omnis
            adipisci soluta magni.
          </p>
        </a>
        <a href="events/Seoul">
          <img src="" alt="" />
          <h2>Events in Seoul</h2>
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Optio hic
            assumenda veniam? Asperiores unde ab possimus alias cum aliquid,
            temporibus qui optio non, doloremque, dignissimos laboriosam omnis
            adipisci soluta magni.
          </p>
        </a>
      </main>

      {/* <footer>
        <p>2023</p>
      </footer> */}
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  // console.log(events_categories);

  return {
    props: {
      data: events_categories,
    },
  };
}
