import Head from "next/head";
import { Inter } from "@next/font/google";
import { HomePage } from "../src/components/home/home-page";
import { Footer } from "../src/components/footer/footer";
import { Header } from "../src/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* home page section */}
      <HomePage props={props} />
    </>
  );
}

export async function getServerSideProps(context: any) {
  const { events_categories } = await import("../data/data.json");

  return {
    props: {
      data: events_categories,
    },
  };
}
